### ISSUE TITLE
Adding a best data management

### ISSUE THREAD

**Issue by johnTheCarrot** [dobobaie/Workers#1]
Can you add a functionality to save easily data in worker ? Maybe something like that : worker.push('myData') or worker.addObject('key', 'value')

**Comment by dobobaie** [comment]
Hi !

I created a package ["data-factory" ](https://www.npmjs.com/package/data-factory) this package let you the possibility to do what you want.

Exemple : 
``` js
const babyWorkers = require('baby-workers');
const dataFactory = require('data-factory');

var workers = new babyWorkers;
workers.create('myData', (worker) => {
	worker._get().push('First push !');
	worker.pop();
}).save(new dataFactory).timeout(200);
workers.complete(() => {
	console.log(workers.myData.get().getStack());
});
```
